# Generated by Django 4.0.4 on 2022-05-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
